DoAnChuyenNganh/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoAnChuyenNganh.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult ViewAbout()
        {
            return View();
        }
    }
}

DoAnChuyenNganh/Views/Shared/MainLayout.cshtml
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<DoAnChuyenNganh.Models.Product>
@{
    ViewBag.Title = "MainLayout";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Pharmative &mdash; Colorlib Template</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/Assets/fonts/icomoon/style.css">

    <link rel="stylesheet" href="~/Assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Assets/fonts/flaticon/font/flaticon.css">
    <link rel="stylesheet" href="~/Assets/css/magnific-popup.css">
    <link rel="stylesheet" href="~/Assets/css/jquery-ui.css">
    <link rel="stylesheet" href="~/Assets/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Assets/css/owl.theme.default.min.css">


    <link rel="stylesheet" href="~/Assets/css/aos.css">

    <link rel="stylesheet" href="~/Assets/css/style.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/AdminLTE-3.1.0/plugins/fontawesome-free/css/all.min.css"
    <!-- IonIcons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/AdminLTE-3.1.0/dist/css/adminlte.min.css">
    <!--Datatables-->
    <link rel="stylesheet" href="~/AdminLTE-3.1.0/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/AdminLTE-3.1.0/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/AdminLTE-3.1.0/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">

</head>

<body>

    <div class="site-wrap">


        <div class="site-navbar py-2">


            @*@using (Html.BeginForm("ViewProduct", "Product", FormMethod.Get))
                {
                    <p>
                        @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
                        <input type="submit" value="Tìm kiếm" />
                    </p>
                }*@
            <div class="search-wrap">
                <div class="container">
                    <a href="#" class="search-close js-search-close"><span class="icon-close2"></span></a>
                    <form action="#" method="post">
                        @*@Html.TextBox("SearchString", ViewBag.CurrentFilter as string)*@
                        <div class="form-inline">
                            <div class="input-group" data-widget="sidebar-search">
                                <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                                <div class="input-group-append">
                                    <button class="btn btn-sidebar">
                                        <i class="fas fa-search fa-fw"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                        @*<input type="submit" value="Tìm kiếm" />*@
                    </form>
                </div>
            </div>



            <div class="container">
                <div class="d-flex align-items-center justify-content-between">
                    <div class="logo">
                        <div class="site-logo">
                            <a href="@Url.Action("Index", "Home")" class="js-logo-clone"> <strong class="text-primary">Minh</strong>Hoàng</a>
                        </div>
                    </div>


                    <div class="main-nav d-none d-lg-block">
                        <nav class="site-navigation text-right text-md-center" role="navigation">
                            <ul class="site-menu js-clone-nav d-none d-lg-block">
                                <li>@Html.ActionLink("Trang Chủ", "Index", "Home")</li>
                                <li>@Html.ActionLink("Của Hàng", "ViewProduct", "Product")</li>


                                @{ Html.RenderAction("RenderMenu", "Home");}



                                <li>@Html.ActionLink("Thông Tin Quầy Thuốc", "ViewAbout", "About")</li>
                                <li>@Html.ActionLink("Liên Lạc", "ViewContact", "Contact")</li>
                            </ul>
                        </nav>
                    </div>


                    <div class="icons">
                        <a href="#" class="icons-btn d-inline-block js-search-open"><span class="icon-search"></span></a>
                        <a href="cart.html" class="icons-btn d-inline-block bag">
                            <span class="icon-shopping-bag"></span>
                            <span class="number">2</span>
                        </a>
                        <a href="#" class="site-menu-toggle js-menu-toggle ml-3 d-inline-block d-lg-none">
                            <span class="icon-menu"></span>
                        </a>
                    </div>
                </div>
            </div>
        </div>



        @RenderBody()
        @{ Html.RenderAction("RenderFooter", "Home");}

    </div>


    <script src="~/Assets/js/jquery-3.3.1.min.js"></script>
    <script src="~/Assets/js/jquery-ui.js"></script>
    <script src="~/Assets/js/popper.min.js"></script>
    <script src="~/Assets/js/bootstrap.min.js"></script>
    <script src="~/Assets/js/owl.carousel.min.js"></script>
    <script src="~/Assets/js/jquery.magnific-popup.min.js"></script>
    <script src="~/Assets/js/aos.js"></script>
    <script src="~/Assets/js/main.js"></script>


</body>
<!-- ./wrapper -->
<!-- REQUIRED SCRIPTS -->
<!-- jQuery -->
<script src="~/AdminLTE-3.1.0/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="~/AdminLTE-3.1.0/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE -->
<script src="~/AdminLTE-3.1.0/dist/js/adminlte.js"></script>

<!-- OPTIONAL SCRIPTS -->
<script src="~/AdminLTE-3.1.0/plugins/chart.js/Chart.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="~/AdminLTE-3.1.0/dist/js/demo.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="~/AdminLTE-3.1.0/dist/js/pages/dashboard3.js"></script>
<!-- jQuery -->
<script src="~/AdminLTE-3.1.0/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="~/AdminLTE-3.1.0/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

<script src="~/Scripts/jquery-1.12.4.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
<script src="~/Scripts/notify.min.js"></script>

<!-- DataTables  & Plugins -->
<script src="~/AdminLTE-3.1.0/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="~/AdminLTE-3.1.0/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="~/AdminLTE-3.1.0/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="~/AdminLTE-3.1.0/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="~/AdminLTE-3.1.0/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="~/AdminLTE-3.1.0/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="~/AdminLTE-3.1.0/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
<script src="~/AdminLTE-3.1.0/plugins/jszip/jszip.min.js"></script>
<script src="~/AdminLTE-3.1.0/plugins/pdfmake/pdfmake.min.js"></script>
<script src="~/AdminLTE-3.1.0/plugins/pdfmake/vfs_fonts.js"></script>
<script src="~/AdminLTE-3.1.0/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="~/AdminLTE-3.1.0/plugins/datatables-buttons/js/buttons.print.min.js"></script>
<script src="~/AdminLTE-3.1.0/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
<script src="~/Scripts/ckeditor/ckeditor/ckeditor.js"></script>
<!-- AdminLTE App -->
<script src="~/AdminLTE-3.1.0/dist/js/adminlte.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="~/AdminLTE-3.1.0/dist/js/demo.js"></script>
<!-- Page specific script -->
<script>
    $(function () {
        $("#example1").DataTable({
            "responsive": true, "lengthChange": false, "autoWidth": false,
            "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
        }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
        $('#example2').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "responsive": true,
        });
    });</script>
</html>

DoAnChuyenNganh/Views/Shared/_Footer.cshtml
<footer class="site-footer bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">

                <div class="block-7">
                    <h3 class="footer-heading mb-4">Giới Thiệu Về <strong class="text-primary">Minh Hoàng</strong></h3>
                    <p>
                        Ở đây có nhiều thuốc Vip và Pro.
                    </p>
                </div>

            </div>
            <div class="col-lg-3 mx-auto mb-5 mb-lg-0">
                <h3 class="footer-heading mb-4">Danh Mục</h3>
                @foreach (var item in ViewBag.category)
                {
                    <ul class="list-unstyled">
                        <li> <a href="@Url.Action("ViewCategory", "Category", new { @id = item.category_id}, null)">@item.category_name</a></li>
                        
                    </ul>
                }
                </div>

            <div class="col-md-6 col-lg-3">
                <div class="block-5 mb-5">
                    <h3 class="footer-heading mb-4">Thông Tin Liên Hệ</h3>
                    <ul class="list-unstyled">
                        <li class="address">Nha Trang</li>
                        <li class="phone"><a href="tel://23923929210">Không Nhớ</a></li>
                        <li class="email">HoangBeDe@gmail.com</li>
                    </ul>
                </div>
            </div>
        </div>

    </div>
</footer>

DoAnChuyenNganh/Views/Shared/_HotproductCSCN.cshtml
@model IEnumerable<DoAnChuyenNganh.Models.Product>
<div class="site-section bg-light">
    <div class="container">
        <div class="row">
            <div class="title-section text-center col-12">
                <h2>Chăm Sóc Cá Nhân<strong class="text-primary"> Mới</strong></h2>
            </div>
        </div>
        <div class="row">

            <div class="col-md-12 block-3 products-wrap">

                <div class="nonloop-block-3 owl-carousel">
                    @foreach (var hot in Model)
                    {
                    <div class="text-center item mb-4 item-v2">
                        @if (hot.product_saleprice < hot.product_imprice)
                        {
                            <span class="onsale">Giảm Giá</span>
                        }
                        else
                        {

                        }
                        <a href="@Url.Action("DetailsProduct","Product",new {id = hot.product_id})"> <img src="~/Assets/images/@hot.product_image" alt="Image"></a>
                        <h3 class="text-dark"><a href="@Url.Action("DetailsProduct","Product",new {id = hot.product_id})">@hot.product_name</a></h3>
                        <p class="price">@hot.product_saleprice</p>
                    </div>
                    }
                </div>

            </div>

        </div>
    </div>
</div>

DoAnChuyenNganh/Views/Shared/_HotproductDMP.cshtml
@model IEnumerable<DoAnChuyenNganh.Models.Product>
<div class="site-section bg-light">
    <div class="container">
        <div class="row">
            <div class="title-section text-center col-12">
                <h2>Dược Mỹ Phẩm<strong class="text-primary"> Mới</strong></h2>
            </div>
        </div>
        <div class="row">

            <div class="col-md-12 block-3 products-wrap">

                <div class="nonloop-block-3 owl-carousel">
                    @foreach (var hot in Model)
                    {
                    <div class="text-center item mb-4 item-v2">
                        @if (hot.product_saleprice < hot.product_imprice)
                        {
                            <span class="onsale">Giảm Giá</span>
                        }
                        else
                        {

                        }
                        <a href="@Url.Action("DetailsProduct","Product",new {id = hot.product_id})"> <img src="~/Assets/images/@hot.product_image" alt="Image"></a>
                        <h3 class="text-dark"><a href="@Url.Action("DetailsProduct","Product",new {id = hot.product_id})">@hot.product_name</a></h3>
                        <p class="price">@hot.product_saleprice</p>
                    </div>
                    }
                </div>

            </div>

        </div>
    </div>
</div>

DoAnChuyenNganh/Views/Shared/_HotproductT.cshtml
@model IEnumerable<DoAnChuyenNganh.Models.Product>
<div class="site-section bg-light">
    <div class="container">
        <div class="row">
            <div class="title-section text-center col-12">
                <h2>Thuốc<strong class="text-primary"> Mới</strong></h2>
            </div>
        </div>
        <div class="row">

            <div class="col-md-12 block-3 products-wrap">

                <div class="nonloop-block-3 owl-carousel">
                    @foreach (var hot in Model)
                    {
                    <div class="text-center item mb-4 item-v2">
                        @if (hot.product_saleprice < hot.product_imprice)
                        {
                            <span class="onsale">Giảm Giá</span>
                        }
                        else
                        {

                        }
                        <a href="@Url.Action("DetailsProduct","Product",new {id = hot.product_id})"> <img src="~/Assets/images/@hot.product_image" alt="Image"></a>
                        <h3 class="text-dark"><a href="@Url.Action("DetailsProduct","Product",new {id = hot.product_id})">@hot.product_name</a></h3>
                        <p class="price">@hot.product_saleprice</p>
                    </div>
                    }
                </div>

            </div>

        </div>
    </div>
</div>

DoAnChuyenNganh/Views/Shared/_HotproductTBYT.cshtml
@model IEnumerable<DoAnChuyenNganh.Models.Product>
<div class="site-section bg-light">
    <div class="container">
        <div class="row">
            <div class="title-section text-center col-12">
                <h2>Thiết Bị Y Tế<strong class="text-primary"> Mới</strong></h2>
            </div>
        </div>
        <div class="row">

            <div class="col-md-12 block-3 products-wrap">

                <div class="nonloop-block-3 owl-carousel">
                    @foreach (var hot in Model)
                    {
                    <div class="text-center item mb-4 item-v2">
                        @if (hot.product_saleprice < hot.product_imprice)
                        {
                            <span class="onsale">Giảm Giá</span>
                        }
                        else
                        {

                        }s
                        <a href="@Url.Action("DetailsProduct","Product",new {id = hot.product_id})"> <img src="~/Assets/images/@hot.product_image" alt="Image"></a>
                        <h3 class="text-dark"><a href="@Url.Action("DetailsProduct","Product",new {id = hot.product_id})">@hot.product_name</a></h3>
                        <p class="price">@hot.product_saleprice</p>
                    </div>
                    }
                </div>

            </div>

        </div>
    </div>
</div>

DoAnChuyenNganh/Views/Shared/_HotproductTPCN.cshtml
@model IEnumerable<DoAnChuyenNganh.Models.Product>
<div class="site-section bg-light">
    <div class="container">
        <div class="row">
            <div class="title-section text-center col-12">
                <h2>Thực Phẩm Chức Năng<strong class="text-primary"> Mới</strong></h2>
            </div>
        </div>
        <div class="row">
            
            <div class="col-md-12 block-3 products-wrap">
                
                <div class="nonloop-block-3 owl-carousel">
                    @foreach (var hot in Model)
                    {
                    <div class="text-center item mb-4 item-v2">
                        @if (hot.product_saleprice < hot.product_imprice)
                        {
                            <span class="onsale">Giảm Giá</span>
                        }
                        else
                        {

                        }
                        <a href="@Url.Action("DetailsProduct","Product",new {id = hot.product_id})"> <img src="~/Assets/images/@hot.product_image" alt="Image"></a>
                        <h3 class="text-dark"><a href="@Url.Action("DetailsProduct","Product",new {id = hot.product_id})">@hot.product_name</a></h3>
                        <p class="price">@hot.product_saleprice</p>
                    </div>
                    }
                    </div>
                
                </div>
                 
            </div>
    </div>
</div>

DoAnChuyenNganh/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DoAnChuyenNganh/Views/Shared/_MenuCategory.cshtml
<li class="has-children">
    <a href="#">Thể Loại</a>
    <ul class="dropdown">
        @foreach (var item in ViewBag.category)
        {
            <li class="has-children">
                <a href="@Url.Action("ViewCategory", "Category", new { @id = item.category_id}, null)">@item.category_name</a>
                <ul class="dropdown">
                    @foreach (var sml in ViewBag.smallcategory)
                    {
                        if (sml.category_id == item.category_id)
                        {
                            <li><a href="@Url.Action("ProductCategory", "Category", new { @id = sml.smallcategory_id }, null)">@sml.smallcategory_name</a></li>
                           
                        }
                        }
                    </ul>
            </li>
        }
        </ul>
</li>