DoAnChuyenNganh/Models/SmallCategory.cs
namespace DoAnChuyenNganh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("SmallCategory")]
    public partial class SmallCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SmallCategory()
        {
            Products = new HashSet<Product>();
        }

        public int category_id { get; set; }

        [Key]
        public int smallcategory_id { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Danh mục")]
        public string smallcategory_name { get; set; }

        //[Display(Name = "Danh mục")]
        public virtual Category Category { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}

DoAnChuyenNganh/Controllers/SmallCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DoAnChuyenNganh.Models;

namespace DoAnChuyenNganh.Controllers
{
    public class SmallCategoriesController : Controller
    {
        private ShopModelContext db = new ShopModelContext();

        // GET: SmallCategories
        public ActionResult Index()
        {
            var smallCategories = db.SmallCategories.Include(s => s.Category);
            return View(smallCategories.ToList());
        }

        // GET: SmallCategories/Create
        public ActionResult Create()
        {
            ViewBag.category_id = new SelectList(db.Categories, "category_id", "category_name");
            return View();
        }

        // POST: SmallCategories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "smallcategory_id,category_id,smallcategory_name")] SmallCategory smallCategory)
        {
            if (ModelState.IsValid)
            {
                db.SmallCategories.Add(smallCategory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.category_id = new SelectList(db.Categories, "category_id", "category_name", smallCategory.category_id);
            return View(smallCategory);
        }

        // GET: SmallCategories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SmallCategory smallCategory = db.SmallCategories.Find(id);
            if (smallCategory == null)
            {
                return HttpNotFound();
            }
            ViewBag.category_id = new SelectList(db.Categories, "category_id", "category_name", smallCategory.category_id);
            return View(smallCategory);
        }

        // POST: SmallCategories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "smallcategory_id,category_id,smallcategory_name")] SmallCategory smallCategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(smallCategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.category_id = new SelectList(db.Categories, "category_id", "category_name", smallCategory.category_id);
            return View(smallCategory);
        }

        // GET: SmallCategories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SmallCategory smallCategory = db.SmallCategories.Find(id);
            if (smallCategory == null)
            {
                return HttpNotFound();
            }
            return View(smallCategory);
        }

        // POST: SmallCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SmallCategory smallCategory = db.SmallCategories.Find(id);
            db.SmallCategories.Remove(smallCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DoAnChuyenNganh/Views/SmallCategories/Create.cshtml
@model DoAnChuyenNganh.Models.SmallCategory

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@using (Html.BeginForm())
{
@Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.smallcategory_name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.smallcategory_name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.smallcategory_name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Danh mục lớn")
        @*@Html.LabelFor(model => model.category_id, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="col-md-10">
            @Html.DropDownList("category_id", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.category_id, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Lưu" class="btn btn-default" />
        </div>
    </div>
</div>}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DoAnChuyenNganh/Views/SmallCategories/Delete.cshtml
@model DoAnChuyenNganh.Models.SmallCategory

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h3>Bạn có muốn xóa</h3>
@ViewBag.Mes
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.smallcategory_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.smallcategory_name)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
@Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Xóa" class="btn btn-default" /> |
                    @Html.ActionLink("Quay lại", "Index")
                </div>}
</div>

DoAnChuyenNganh/Views/SmallCategories/Edit.cshtml
@model DoAnChuyenNganh.Models.SmallCategory

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@using (Html.BeginForm())
{
@Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.smallcategory_id)

    <div class="form-group">
        @Html.LabelFor(model => model.smallcategory_name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.smallcategory_name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.smallcategory_name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Danh mục lớn")
        @*@Html.LabelFor(model => model.category_id, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="col-md-10">
            @Html.DropDownList("category_id", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.category_id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Lưu" class="btn btn-default" />
        </div>
    </div>
</div>}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DoAnChuyenNganh/Views/SmallCategories/Index.cshtml
@model IEnumerable<DoAnChuyenNganh.Models.SmallCategory>


@{ ViewBag.Title = "Index";
                Layout = "~/Views/Shared/_LayoutAdmin.cshtml"; }

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <!-- /.card-header -->
                    <div class="card-body">
                        <a class="btn btn-success" onclick="confirmAction()" style="margin-bottom:10px" href="@Url.Action("Create","SmallCategories")"><i class="fa fa-plus"></i></a>
                        <table id="example1" class="table table-bordered table-striped" method="Get">
                            <thead>
                                <tr>
                                    <th>@Html.DisplayNameFor(model => model.smallcategory_name)</th>
                                    <th>Số lượng</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.smallcategory_name)
                                    </td>
                                    @*<td>
            <a href="/Products/GetProductById/@item.category_id">@Html.DisplayFor(m => item.Products.Count)</a>
        </td>*@
                                    <td>
                                        @Html.DisplayFor(m => item.Products.Count)
                                    </td>
                                    <td>
                                        <a class='btn btn-default btn-sm' style='margin-left:5px' href="/SmallCategories/Edit/@item.smallcategory_id"><i class='fa fa-edit'></i> Sửa</a>
                                        @if (@item.Products.Count.Equals(0))
                                        {
                                <a class='btn btn-danger btn-sm' style='margin-left:5px' href="/SmallCategories/Delete/@item.smallcategory_id"><i class='fa fa-trash'></i> Xóa</a>}
                                    </td>

                                </tr>}
                            </tbody>
                            
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>