DoAnChuyenNganh/Models/Origin.cs
namespace DoAnChuyenNganh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Origin")]
    public partial class Origin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Origin()
        {
            Products = new HashSet<Product>();
        }

        [Key]
        [Display(Name ="Mã nước xuât xứ")]
        public int origin_id { get; set; }

        [StringLength(50)]
        [Display(Name = "Xuât xứ")]
        public string origin_name { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}

DoAnChuyenNganh/Controllers/OriginsController.cs
using DoAnChuyenNganh.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace DoAnChuyenNganh.Controllers
{
    public class OriginsController : Controller
    {
        private ShopModelContext db = new ShopModelContext();
        // GET: Origins
        public ActionResult Index()
        {
            return View(db.Origins.ToList());
        }

 
        // GET: Origins/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Origins/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "origin_id,origin_name")] Origin origin)
        {
            if (ModelState.IsValid)
            {
                db.Origins.Add(origin);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(origin);
        }

        // GET: Origins/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Origin origin = db.Origins.Find(id);
            if (origin == null)
            {
                return HttpNotFound();
            }
            return View(origin);
        }

        // POST: Origins/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "origin_id,origin_name")] Origin origin)
        {
            if (ModelState.IsValid)
            {
                db.Entry(origin).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(origin);
        }

        // GET: Origins/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Origin origin = db.Origins.Find(id);
            if (origin == null)
            {
                return HttpNotFound();
            }
            return View(origin);
        }

        // POST: Origins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
           
            Origin origin = db.Origins.Find(id);
            db.Origins.Remove(origin);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DoAnChuyenNganh/Views/Origins/Create.cshtml
@model DoAnChuyenNganh.Models.Origin

@{ ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml"; }

@using (Html.BeginForm())
{
@Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                    <div class="form-group">
                        @Html.LabelFor(model => model.origin_name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.origin_name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.origin_name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Tạo mới" class="btn btn-default" />
                        </div>
                    </div>
                </div>}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DoAnChuyenNganh/Views/Origins/Delete.cshtml
@model DoAnChuyenNganh.Models.Origin

@{ ViewBag.Title = "Delete";
                Layout = "~/Views/Shared/_LayoutAdmin.cshtml"; }

<h3>Bạn có muốn xóa ?</h3>
@ViewBag.Mes
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.origin_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.origin_name)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
@Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Xóa" class="btn btn-default" /> |
                    @Html.ActionLink("Quay lại", "Index")
                </div>}
</div>

DoAnChuyenNganh/Views/Origins/Edit.cshtml
@model DoAnChuyenNganh.Models.Origin

@{ ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml"; }

@using (Html.BeginForm())
{
@Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.origin_id)

                    <div class="form-group">
                        @Html.LabelFor(model => model.origin_name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.origin_name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.origin_name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Lưu" class="btn btn-default" />
                        </div>
                    </div>
                </div>}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DoAnChuyenNganh/Views/Origins/Index.cshtml
@model IEnumerable<DoAnChuyenNganh.Models.Origin>

@{ ViewBag.Title = "Index";
                Layout = "~/Views/Shared/_LayoutAdmin.cshtml"; }

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <!-- /.card-header -->
                    <div class="card-body">
                        <a class="btn btn-success" onclick="confirmAction()" style="margin-bottom:10px" href="@Url.Action("Create","Origins")"><i class="fa fa-plus"></i></a>
                        <table id="example1" class="table table-bordered table-striped" method="Get">
                            <thead>
                                <tr>
                                    <th>@Html.DisplayNameFor(model => model.origin_name)</th>
                                    <th>Số lượng</th>
                                    <th></th>

                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.origin_name)
                        </td>
                        <td>
                            @Html.DisplayFor(m => item.Products.Count)
                        </td>
                        <td>
                            <a class='btn btn-default btn-sm' style='margin-left:5px' href="/Origins/Edit/@item.origin_id"><i class='fa fa-edit'></i> Sửa</a>
                            @if (@item.Products.Count.Equals(0))
                            {
            <a class='btn btn-danger btn-sm' style='margin-left:5px' href="/Origins/Delete/@item.origin_id"><i class='fa fa-trash'></i> Xóa</a>}
                        </td>

                    </tr>}
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>